import type { Metadata } from "next";
import "./globals.css";
// import "@material-design-icons/font";
import { Suspense } from "react";
import QueryProvider from "@web/src/components/QueryProvider";
import { ErrorBoundary } from "react-error-boundary";
import SonnerToaster from "@web/src/components/ui/SonnerToaster";
import GlobalHeader from "@web/src/components/layout/GlobalHeader";
import GlobalSidebar from "@web/src/components/layout/GlobalSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-surface-container min-h-screen flex flex-col text-on-background">
        <QueryProvider>
          <ErrorBoundary fallback={<div>Something went wrong</div>}>
            <Suspense fallback="loading...">
              <SonnerToaster />
              <GlobalHeader />
              <div className="flex h-full flex-auto">
                <div className="w-0 xl:w-64 transition-all">
                  <GlobalSidebar className="w-0 xl:w-64 transition-all" />
                </div>
                <main className="flex-auto flex p-4 pt-0">{children}</main>
              </div>
            </Suspense>
          </ErrorBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
