import type { Metadata } from "next";
import "./globals.css";
// import "@material-design-icons/font";
import { Suspense } from "react";
import QueryProvider from "@web/src/components/QueryProvider";
import { ErrorBoundary } from "react-error-boundary";
import SonnerToaster from "@web/src/components/ui/SonnerToaster";
import GlobalHeader from "@web/src/components/global/GlobalHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <QueryProvider>
          <ErrorBoundary fallback={<div>Something went wrong</div>}>
            <Suspense fallback="loading...">
              <SonnerToaster />
              <GlobalHeader />
              <main>{children}</main>
            </Suspense>
          </ErrorBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
