import type { Metadata } from "next";
import "./globals.css";
// import "@material-design-icons/font";
import { Suspense } from "react";
import QueryProvider from "@/src/shared/components/query-provider";
import { ErrorBoundary } from "react-error-boundary";
import SonnerToaster from "@/src/shared/components/ui/sonner-toaster";
import { GoogleLoginProvider } from "@/src/auth/hooks/use-google-login";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="referrer" content="no-referrer-when-downgrade" />
      </Head>
      <body className="bg-surface-container min-h-screen flex flex-col text-on-background">
        <ErrorBoundary fallback={<div>Something went wrong</div>}>
          <QueryProvider>
            <GoogleLoginProvider>
              <Suspense fallback="loading...">
                <SonnerToaster />
                {children}
              </Suspense>
            </GoogleLoginProvider>
          </QueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
